/* 
    - `focal-elf-631.standard_report_v1_view.report_final_skan` 
    - MCP SKAN performance data

    SCHEMA:
        - Time_Bucket (TIMESTAMP)
        - platform
        - Advertiser_ID
        - Product_ID
        - Campaign_ID
        - AdGroup_ID
        - CreativeGroup_ID
        - Attribution_Type
        - Impressions
        - Clicks
        - Installs
        - Spend
        - Revenue
        - Conversion_Event
        - Conversion_Count
        - Conversion_Revenue
        - Traffic_LAT
        - Traffic_SKANReq
        - Traffic_SKANBid
        - Traffic_MMPEffective
        - SKAN_ConversionValue
        - SKAN_ConversionCount
        - SKAN_CampaignID
        - SKAN_CampaignTrSuffix	STRING	NULLABLE
        - SKAN_ConversionEvent	STRING	NULLABLE
        - SKAN_ConversionEventCount	INTEGER	NULLABLE
        - SKAN_Version	STRING	NULLABLE
        - SKAN_Fidelity_Type	INTEGER	NULLABLE
        - SKAN_ConversionEventRevenueMinSum	NUMERIC	NULLABLE
        - SKAN_ConversionEventRevenueMaxSum
        - SKAN_DidWin	BOOLEAN	NULLABLE
        - SKAN_SourceIdentifier	STRING	NULLABLE
        - SKAN_CoarseConversionValue	STRING	NULLABLE
        - SKAN_PostbackSequenceIndex	INTEGER	NULLABLE
        - SKAN_Redownload	BOOLEAN	NULLABLE
    - 
*/